all: %

ex_binarytree: ex_binarytree.c
	gcc -Wall -O0 -o $@ $<

ordering: ordering.c
	gcc -Wall -O0 -o $@ $<

calculator: calculator.c
	gcc -Wall -O0 -o $@ $<

dic: dic.c
	gcc -Wall -O0 -o $@ $<

clean:
	rm ex_binarytree ordering calculator dic

