all: %

ex_binarytree: ex_binarytree.c
	gcc -Wall -O0 -o $@ $<

ordering: ordering.c
	gcc -Wall -O0 -o $@ $<

calculator: calculator.c
	gcc -Wall -O0 -o $@ $<

dic: dic.c
	gcc -Wall -O0 -o $@ $<

BST-demo: BST_demo
	gcc -Wall -O0 -g $@ $<
 
clean:
	rm ex_binarytree ordering calculator dic BST_demo

